### PR TITLE
refactor: necromancy to restore MV2 build

### LINKED ISSUE #878: Switch precache to better locality check
Right now we list all local CIDs via `ipfs refs local` and its not efficient to do on a big repo:

https://github.com/ipfs-shipyard/ipfs-companion/blob/793bd6cdbe804f611ed42f7dd32c6fb8d9d224b8/add-on/src/lib/precache.js#L36-L40

### Idea A

As noted [here](https://discuss.ipfs.io/t/question-whats-the-most-efficient-way-to-check-if-the-blocks-of-a-cid-exist-locally/7820/9?u=lidel) we could improve `inRepo` check and run regular `ipfs refs -r --offline` if there was no error that means the _entire_ DAG is present in local repo. 

Caveat: `--offline` works only in go-ipfs CLI, missing from JS API does not https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/REFS.md#ipfsrefslocaloptions

### Idea B

below works in go-ipfs, showing % of local vs remote 
`ipfs files stat --with-local --size /ipfs/bafybeigkbbjnltbd4ewfj7elajsbnjwinyk6tiilczkqsibf3o7dcr6nn4`

### Idea C

`ipfs block stat --offline <cid>` will return error if CID is not already present in the datastore

TODO: check if implemented in js-ipfs and updated [this forum thread](https://discuss.ipfs.io/t/question-whats-the-most-efficient-way-to-check-if-the-blocks-of-a-cid-exist-locally/7820/10) for visibility.

### LINKED ISSUE #1059: go-ipfs 0.12 interop
Ref. https://github.com/ipfs/go-ipfs/releases/tag/v0.12.0

- [ ] check if our webui preload  logic is impacted by `refs local` change or not

### PR DESCRIPTION
**Pull request by lidel**
This PR:
-  removes a lot of unused functionality (windows.ipfs proxy logic) which has been deprecated and disabled for years, which in turn removed a bunch of deps
- removes yarn (Node we now has `npm ci` and `package-lock.json` which should be good enough)

## TODO

- [x] remove yarn and all the hackery around transitive dependency overrides
- [x] bump all dependencies
- [x] switch to ipfs-core for fewer deps
- [x] remove unused deps
- [x] Firefox manifest fix to pass latest webext lint
- [x] remove remaining window.ipfs code that was pulling dead dependencies
  (https://github.com/ipfs/in-web-browsers/issues/172)
- [x] ensure https://github.com/ipfs/ipfs-companion/pull/1070 is ported (if still relevant)
- [x] fix tests (they fail due to ESM error)
  - :point_right:  TBD, but  we may need to refactor things to ESM and just call it a day anyway
    - we removed `jest` from ipfs-webui e2e tests and [replaced it with `playwright`](https://github.com/ipfs/ipfs-webui/blob/main/test/e2e/playwright.config.js) 
- [x] docker builds (bump to latest nodejs)
- [x] browserAction icon (it is always "inactive" now) – fixed in 4e1704372f5973abbfaae6063a401dbdb595d846
- [x] something about is-ipfs  (update?)
- [ ] <del>quick import with js-ipfs works</del> was broken in main  – can be fixed in separate PR  (or removed)
- [ ] confirm import of an image via context menu works (addFromURL)
- [x] confirm webui preload logic works (should check if CID is in datastore and preload only if it is) – closes #1059 closes #878
- [x] cleanup: remove any left-overs from window.ipfs logic – done in https://github.com/ipfs/ipfs-companion/pull/1054/commits/830ae1f017255f9218c7173a2d21c69aa1b98dd5, see https://github.com/ipfs/ipfs-companion/issues/589#issuecomment-712356448
- [x] confirm Brave onboarding works 
- [x] update client so `swarm.peers` don't fail on webtransport – a96cf2049e13c34f7a4eeab2cc93bd436d6426b6
- [x] fix the way `debug` is initialized, so  namespaces are applied before companion is initialized – a96cf2049e13c34f7a4eeab2cc93bd436d6426b6
- [x] work and require latest Node LTS

### CODE REVIEW

**Comment by lidel** [comment]
cc @meandavejustice  @SgtPooki @whizzzkid (just FYI  – no immediate action needed)

This PR includes a cleanup which I did not finish (mostly works, but tests do not run due to ESM).

If any of you ever starts updating dependencies in this project, this PR will be useful prior art to see which dependencies and deprecated code blocks can be removed to reduce maintenance cost going forward.

**Comment by tinytb** [comment]
2022-10-20 chat with lidel
- Let's land this PR and then make a release.
- This creates a clean slate so that new contributors don't need to worry about as much dead code that needs to be removed.
- Nishant can help with landing this -- lidel hasn't look at this in a month.
- Bump dependencies, see that it builds, and make sure the tests pass.
- Should do this before the end of the year; the sooner, the better.
- Ensures that when we are ready with ManifestV3, we can make a release.
- Have a working version that we can revert to, if there's an issue with the ManifestV3 upgrade.

**Comment by lidel** [comment]
Late thought: if fixing mocha tests is a lot of work we can consider removing it and replacing it with [@playwright/test](https://www.npmjs.com/package/@playwright/test) like we did in ipfs-webui.

**Comment by whizzzkid** [comment]
@lidel https://github.com/ipfs/ipfs-companion/pull/1101 fixes most of the issues, the only problem I'm facing is https://github.com/mozilla/webextension-polyfill/issues/236

Which doesn't seem to be working. Will be spending some more time on this.

**Comment by lidel** [comment]
Thanks to @whizzzkid's  help in https://github.com/ipfs/ipfs-companion/pull/1101 I managed to focus on closing remaining cleanup. 

Historical issues I was able to identify are resolved. 
Merging so we can plan making a new release before EOY.

**Pull request merged**
