### PR TITLE
fix: linkify tests

### LINKED ISSUE #1050: Linkify experimental feature - demo page shows unlinked "should be linkified" text
**Describe the bug**

**To Reproduce**
1. Go to the [linkify-demo page](https://ipfs.io/ipfs/bafybeidvtwx54qr44kidymvhfzefzxhgkieigwth6oswk75zhlzjdmunoy/linkify-demo.html)
2. Notice that "ipns://ipfs.git.sexy" is not linkified (see screenshot below)

**Expected behavior**

All links under "Should be linkified" should be linkified.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.1 (21C52)
 - Browser: Chrome 
 - Version: 97.0.4692.99 (Official Build) (arm64)

**Additional context**

One of two fixes:

1. "ipns://ipfs.git.sexy" should be linkified.
or
2. "ipns://ipfs.git.sexy" should not be listed under the "Should be linkified section"

### PR DESCRIPTION
**Pull request by SgtPooki**
fix #1050

### CODE REVIEW

**Review by lidel — APPROVED** [review]
Thanks!

**Review by kaka1365 — COMMENTED** [review]
Good

**Comment by kaka1365** [comment]
Oki

**Review by kaka1365 — COMMENTED** [review]
Good

**Pull request merged**
